using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Homework.Account;
using MVC_Homework.Models.ViewModels;

namespace MVC_Homework.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult KeepAccounts()
        {
            ViewBag.Message = "記帳";
            return View();
        }
        
        public ActionResult BillPage(AccountViewModel Bill)
        {
            var fakeDataGen = new AutoGenerateData();
            var fakeData = fakeDataGen.GenerateData();
            return View(fakeData);
        }
    }
}